-- 코드를 입력하세요
SELECT info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS, ROUND(AVG(re.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO as info
INNER JOIN REST_REVIEW as re
ON info.REST_ID = re.REST_ID
WHERE info.ADDRESS like '서울%'
GROUP BY info.REST_ID
ORDER BY SCORE DESC, info.FAVORITES DESC;